# Non-secure properties file:
#
ns:
  email: "demos+sfdc5netsuite@mulesoft.com"

# polling interval is in milliseconds
sfdc:
  polling_interval: "5000"
  auth_url: "https://db000000061wgmaq.my.salesforce.com/services/Soap/u/50.0"