# Secure Properties File
#
# NetSuite properties for the demo5 user:
ns:
  account: "![uc7rDe+qWXL9WTWI7s7UZQ==]"
  user: "![Jf1gJX/W5ztX4LVRIjQXKbsggI30ckH0Ml0kWn+sfdpY9yVJRlKzYg==]"
  pass: "![xBAiAbZhSCoTUohzkb5QPw==]"
  applicationId: "![5caWhKEg5KJ8P1NB8C/mjJLQPgoMwEj6y75wEDBMfOe+Ve1cyp5CYA==]"
  roleId: "![k8EFiouhuU0=]"
  
# Salesforce properties - 228 GA version sandbox:
sfdc:
  user: "![d5HIVDGMXBLihFkkLN0dPXoJi5RKdhCDl2pqTMBL/8kolqvk6B4ZBw==]"
  password: "![U8KM0WZEG3vz2Thm48oPQQ==]"