# Non-secure properties file:
#
# polling interval is in milliseconds
sfdc:
  polling_interval: "5000"
  auth_url: "INSERT AUTHORIZATION URL HERE... ie: https://login.salesforce.com/services/Soap/u/50.0"